# ---------------------------------------------------------------------------
# Cloud Run Jobs — one per report type
# ---------------------------------------------------------------------------
# Dependencies (defined in BQ DS + Tables.tf):
#   google_secret_manager_secret.gitlab_token  (token value loaded manually)
#   google_bigquery_dataset.devops_reports
#   google_storage_bucket.devops_reports
#
# EXECUTION_ID is auto-generated by entrypoint.sh on every run — no static
# value is needed here.
# ---------------------------------------------------------------------------

locals {
  runner_sa       = var.cloud_run_sa_email
  job_region      = var.region
  job_project     = var.project_id
  job_image       = var.container_image
  job_memory      = "2Gi"
  job_cpu         = "1"
  job_timeout     = "3600s"
  job_max_retries = 0

  # env_drift runs multiple repos in parallel (entrypoint.sh caps concurrency via
  # ENV_DRIFT_MAX_PARALLEL below) — needs more headroom than the single-process jobs,
  # which previously shared job_memory/job_cpu and were getting OOM-killed.
  env_drift_memory       = "4Gi"
  env_drift_cpu          = "2"
  env_drift_max_parallel = "5"
}

# ---------------------------------------------------------------------------
# Job 1: Orphan Datasets
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "orphan_datasets" {
  name     = "devops-reports-orphan-datasets"
  location = local.job_region
  project  = local.job_project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.job_timeout
      max_retries     = local.job_max_retries

      containers {
        image = local.job_image

        args = [
          "orphan_datasets",
          "--project-id",        var.bq_scan_project_id,
          "--gcp-project",       var.project_id,
          "--reporting-project", var.reporting_project_id,
          "--gcs-bucket",        var.reports_gcs_bucket,
        ]

        env {
          name  = "GCP_PROJECT"
          value = var.project_id
        }
        env {
          name  = "GITLAB_BASE_URL"
          value = var.gitlab_base_url
        }
        env {
          name  = "GITLAB_TOKEN_SECRET_ID"
          value = var.gitlab_token_secret_id
        }
        env {
          name  = "SUBGROUP"
          value = var.gitlab_subgroup
        }

        resources {
          limits = {
            memory = local.job_memory
            cpu    = local.job_cpu
          }
        }
      }

      vpc_access {
        connector = data.google_vpc_access_connector.devops_reports.id
        egress    = "ALL_TRAFFIC"
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Job 2: Environment vs Code Drift
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "env_drift" {
  name     = "devops-reports-env-drift"
  location = local.job_region
  project  = local.job_project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.job_timeout
      max_retries     = local.job_max_retries

      containers {
        image = local.job_image

        args = [
          "env_drift",
          "--gcp-project",        var.project_id,
          "--reporting-project",  var.reporting_project_id,
          "--reports-gcs-bucket", var.reports_gcs_bucket,
        ]

        env {
          name  = "GCP_PROJECT"
          value = var.project_id
        }
        env {
          name  = "GITLAB_BASE_URL"
          value = var.gitlab_base_url
        }
        env {
          name  = "GITLAB_TOKEN_SECRET_ID"
          value = var.gitlab_token_secret_id
        }
        env {
          name  = "SUBGROUP"
          value = var.gitlab_subgroup
        }
        env {
          name  = "ENV_DRIFT_MAX_PARALLEL"
          value = local.env_drift_max_parallel
        }

        resources {
          limits = {
            memory = local.env_drift_memory
            cpu    = local.env_drift_cpu
          }
        }
      }

      vpc_access {
        connector = data.google_vpc_access_connector.devops_reports.id
        egress    = "ALL_TRAFFIC"
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Job 3: Commit-Based Branch Drift
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "commit_drift" {
  name     = "devops-reports-commit-drift"
  location = local.job_region
  project  = local.job_project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.job_timeout
      max_retries     = local.job_max_retries

      containers {
        image = local.job_image

        args = [
          "commit_drift",
          "--gcp-project",       var.project_id,
          "--reporting-project", var.reporting_project_id,
          "--gcs-bucket",        var.reports_gcs_bucket,
        ]

        env {
          name  = "GCP_PROJECT"
          value = var.project_id
        }
        env {
          name  = "GITLAB_BASE_URL"
          value = var.gitlab_base_url
        }
        env {
          name  = "GITLAB_TOKEN_SECRET_ID"
          value = var.gitlab_token_secret_id
        }
        env {
          name  = "SUBGROUP"
          value = var.gitlab_subgroup
        }

        resources {
          limits = {
            memory = local.job_memory
            cpu    = local.job_cpu
          }
        }
      }

      vpc_access {
        connector = data.google_vpc_access_connector.devops_reports.id
        egress    = "ALL_TRAFFIC"
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Job 4: File-Content Branch Drift
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "file_drift" {
  name     = "devops-reports-file-drift"
  location = local.job_region
  project  = local.job_project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.job_timeout
      max_retries     = local.job_max_retries

      containers {
        image = local.job_image

        args = [
          "file_drift",
          "--gcp-project",       var.project_id,
          "--reporting-project", var.reporting_project_id,
          "--gcs-bucket",        var.reports_gcs_bucket,
        ]

        env {
          name  = "GCP_PROJECT"
          value = var.project_id
        }
        env {
          name  = "GITLAB_BASE_URL"
          value = var.gitlab_base_url
        }
        env {
          name  = "GITLAB_TOKEN_SECRET_ID"
          value = var.gitlab_token_secret_id
        }
        env {
          name  = "SUBGROUP"
          value = var.gitlab_subgroup
        }

        resources {
          limits = {
            memory = local.job_memory
            cpu    = local.job_cpu
          }
        }
      }

      vpc_access {
        connector = data.google_vpc_access_connector.devops_reports.id
        egress    = "ALL_TRAFFIC"
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
output "orphan_datasets_job_name" {
  value = google_cloud_run_v2_job.orphan_datasets.name
}

output "env_drift_job_name" {
  value = google_cloud_run_v2_job.env_drift.name
}

output "commit_drift_job_name" {
  value = google_cloud_run_v2_job.commit_drift.name
}

output "file_drift_job_name" {
  value = google_cloud_run_v2_job.file_drift.name
}

output "reports_runner_sa_email" {
  value = var.cloud_run_sa_email
}
