# ---------------------------------------------------------------------------
# Cloud Run Jobs — one per report type
# ---------------------------------------------------------------------------
# Dependencies (defined in BQ DS + Tables.tf):
#   google_service_account.reports_runner
#   google_secret_manager_secret.gitlab_token  (token value loaded manually)
#   google_bigquery_dataset.devops_reports
#   google_storage_bucket.devops_reports
#
# EXECUTION_ID is auto-generated by entrypoint.sh on every run — no static
# value is needed here.
# ---------------------------------------------------------------------------

locals {
  runner_sa   = google_service_account.reports_runner.email
  reports_job_defaults = {
    region      = var.region
    project     = var.project_id
    image       = var.container_image
    memory      = "2Gi"
    cpu         = "1"
    timeout     = "3600s"
    max_retries = 1
  }
}

# ---------------------------------------------------------------------------
# Job 1: Orphan Datasets
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "orphan_datasets" {
  name     = "devops-reports-orphan-datasets"
  location = local.reports_job_defaults.region
  project  = local.reports_job_defaults.project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.reports_job_defaults.timeout
      max_retries     = local.reports_job_defaults.max_retries

      containers {
        image = local.reports_job_defaults.image

        args = [
          "orphan_datasets",
          "--gcp-project",        var.project_id,
          "--reporting-project",  var.reporting_project_id,
          "--gcs-bucket",         var.reports_gcs_bucket,
        ]

        env { name = "GCP_PROJECT";            value = var.project_id }
        env { name = "GITLAB_BASE_URL";        value = var.gitlab_base_url }
        env { name = "GITLAB_TOKEN_SECRET_ID"; value = var.gitlab_token_secret_id }
        env { name = "SUBGROUP";               value = var.gitlab_subgroup }

        resources {
          limits = {
            memory = local.reports_job_defaults.memory
            cpu    = local.reports_job_defaults.cpu
          }
        }
      }

      dynamic "vpc_access" {
        for_each = var.vpc_connector != null ? [var.vpc_connector] : []
        content {
          connector = vpc_access.value
          egress    = "ALL_TRAFFIC"
        }
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Job 2: Environment vs Code Drift
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "env_drift" {
  name     = "devops-reports-env-drift"
  location = local.reports_job_defaults.region
  project  = local.reports_job_defaults.project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.reports_job_defaults.timeout
      max_retries     = local.reports_job_defaults.max_retries

      containers {
        image = local.reports_job_defaults.image

        args = [
          "env_drift",
          "--gcp-project",         var.project_id,
          "--reporting-project",   var.reporting_project_id,
          "--reports-gcs-bucket",  var.reports_gcs_bucket,
        ]

        env { name = "GCP_PROJECT";            value = var.project_id }
        env { name = "GITLAB_BASE_URL";        value = var.gitlab_base_url }
        env { name = "GITLAB_TOKEN_SECRET_ID"; value = var.gitlab_token_secret_id }
        env { name = "SUBGROUP";               value = var.gitlab_subgroup }

        resources {
          limits = {
            memory = local.reports_job_defaults.memory
            cpu    = local.reports_job_defaults.cpu
          }
        }
      }

      dynamic "vpc_access" {
        for_each = var.vpc_connector != null ? [var.vpc_connector] : []
        content {
          connector = vpc_access.value
          egress    = "ALL_TRAFFIC"
        }
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Job 3: Commit-Based Branch Drift
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "commit_drift" {
  name     = "devops-reports-commit-drift"
  location = local.reports_job_defaults.region
  project  = local.reports_job_defaults.project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.reports_job_defaults.timeout
      max_retries     = local.reports_job_defaults.max_retries

      containers {
        image = local.reports_job_defaults.image

        args = [
          "commit_drift",
          "--gcp-project",       var.project_id,
          "--reporting-project", var.reporting_project_id,
          "--gcs-bucket",        var.reports_gcs_bucket,
        ]

        env { name = "GCP_PROJECT";            value = var.project_id }
        env { name = "GITLAB_BASE_URL";        value = var.gitlab_base_url }
        env { name = "GITLAB_TOKEN_SECRET_ID"; value = var.gitlab_token_secret_id }
        env { name = "SUBGROUP";               value = var.gitlab_subgroup }

        resources {
          limits = {
            memory = local.reports_job_defaults.memory
            cpu    = local.reports_job_defaults.cpu
          }
        }
      }

      dynamic "vpc_access" {
        for_each = var.vpc_connector != null ? [var.vpc_connector] : []
        content {
          connector = vpc_access.value
          egress    = "ALL_TRAFFIC"
        }
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Job 4: File-Content Branch Drift
# ---------------------------------------------------------------------------
resource "google_cloud_run_v2_job" "file_drift" {
  name     = "devops-reports-file-drift"
  location = local.reports_job_defaults.region
  project  = local.reports_job_defaults.project

  depends_on = [google_project_service.run]

  template {
    template {
      service_account = local.runner_sa
      timeout         = local.reports_job_defaults.timeout
      max_retries     = local.reports_job_defaults.max_retries

      containers {
        image = local.reports_job_defaults.image

        args = [
          "file_drift",
          "--gcp-project",       var.project_id,
          "--reporting-project", var.reporting_project_id,
          "--gcs-bucket",        var.reports_gcs_bucket,
        ]

        env { name = "GCP_PROJECT";            value = var.project_id }
        env { name = "GITLAB_BASE_URL";        value = var.gitlab_base_url }
        env { name = "GITLAB_TOKEN_SECRET_ID"; value = var.gitlab_token_secret_id }
        env { name = "SUBGROUP";               value = var.gitlab_subgroup }

        resources {
          limits = {
            memory = local.reports_job_defaults.memory
            cpu    = local.reports_job_defaults.cpu
          }
        }
      }

      dynamic "vpc_access" {
        for_each = var.vpc_connector != null ? [var.vpc_connector] : []
        content {
          connector = vpc_access.value
          egress    = "ALL_TRAFFIC"
        }
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
output "orphan_datasets_job_name" {
  value = google_cloud_run_v2_job.orphan_datasets.name
}

output "env_drift_job_name" {
  value = google_cloud_run_v2_job.env_drift.name
}

output "commit_drift_job_name" {
  value = google_cloud_run_v2_job.commit_drift.name
}

output "file_drift_job_name" {
  value = google_cloud_run_v2_job.file_drift.name
}

output "reports_runner_sa_email" {
  value = google_service_account.reports_runner.email
}
